#!/usr/bin/env python3
"""
ENDURANCE HRV v4 — Generación histórica completa
=================================================
Genera los 3 archivos v4 a partir de datos históricos disponibles:
  1. ENDURANCE_HRV_master_FINAL_v4.csv     (58 cols: incluye auditoría raw-vs-ref)
  2. ENDURANCE_HRV_master_DASHBOARD_v4.csv  (10 cols: 9 originales + reason_text)
3. ENDURANCE_HRV_sleep.csv                (sueño Polar + métricas derivadas)

Usa como entrada:
  - CORE completo (274 días)
  - Sleep data del reviewer merge (263 noches básicas, 50 con score/nightly)
  - Intervals activities raw (304 sesiones, 239 días)
"""

import os
import sys
import numpy as np
import pandas as pd
from pathlib import Path
from typing import Tuple, List, Optional, Dict

# =============================================================================
# PART 0: Load all data sources
# =============================================================================

def load_all_sources():
    """Load and prepare all data sources."""
    
    # CORE (274 days)
    core = pd.read_csv("/home/claude/ENDURANCE_HRV_master_CORE_274.csv")
    core['Fecha'] = core['Fecha'].astype(str)
    
    # Reviewer's merge (has sleep + intervals already merged)
    rev = pd.read_csv("/mnt/user-data/uploads/ENDURANCE_HRV_master_FINAL_plus_sleep_intervals_preview.csv")
    rev['Fecha'] = rev['Fecha'].astype(str)
    
    # Raw intervals activities (for load_3d calculation)
    acts = pd.read_csv("/mnt/user-data/uploads/i22348_activities.csv")
    acts['Fecha'] = pd.to_datetime(acts['Date']).dt.strftime('%Y-%m-%d')
    
    return core, rev, acts


# =============================================================================
# PART 1: Build sleep.csv from historical data
# =============================================================================

def build_context(rev: pd.DataFrame, acts: pd.DataFrame) -> pd.DataFrame:
    """
    Build ENDURANCE_HRV_sleep.csv from historical exports.

    v4: sleep.csv = Polar sleep/nightly ONLY.
    Training load is in sessions_day.csv (generated by build_sessions.py).
    """
    
    # --- Polar sleep: from reviewer merge ---
    sleep_cols = [
        'Fecha',
        'sleep_score', 'sleep_continuity', 'sleep_efficiency',
        'sleep_rem', 'sleep_n3', 'sleep_long_interruptions',
        'sleep_span', 'asleep_duration',
        'nightly_rmssd', 'nightly_rri', 'nightly_resp_int',
    ]
    rev_sleep = rev[[c for c in sleep_cols if c in rev.columns]].copy()
    
    # Parse durations to minutes
    def iso_dur_to_min(val):
        if pd.isna(val) or val == '':
            return np.nan
        s = str(val)
        if s.startswith('PT'):
            s = s[2:]
            hours = 0
            mins = 0
            if 'H' in s:
                parts = s.split('H')
                hours = float(parts[0])
                s = parts[1]
            if 'M' in s:
                parts = s.split('M')
                mins = float(parts[0])
                s = parts[1] if len(parts) > 1 else ''
            secs = 0
            if 'S' in s:
                secs = float(s.replace('S', ''))
            return hours * 60 + mins + secs / 60
        return np.nan
    
    if 'asleep_duration' in rev_sleep.columns:
        rev_sleep['polar_sleep_duration_min'] = rev_sleep['asleep_duration'].apply(iso_dur_to_min)
    if 'sleep_span' in rev_sleep.columns:
        rev_sleep['polar_sleep_span_min'] = rev_sleep['sleep_span'].apply(iso_dur_to_min)
    
    # Rename to context schema
    rename_map = {
        'sleep_score': 'polar_sleep_score',
        'sleep_continuity': 'polar_continuity',
        'sleep_efficiency': 'polar_efficiency_pct',
        'sleep_rem': 'polar_rem_pct',
        'sleep_n3': 'polar_deep_pct',
        'sleep_long_interruptions': 'polar_interruptions_long',
        'nightly_rmssd': 'polar_night_rmssd',
        'nightly_rri': 'polar_night_rri',
        'nightly_resp_int': 'polar_night_resp',
    }
    rev_sleep = rev_sleep.rename(columns={k: v for k, v in rename_map.items() if k in rev_sleep.columns})
    
    # Efficiency from raw data if available
    if 'efficiency_pct' in rev.columns:
        rev_sleep['polar_efficiency_pct'] = rev['efficiency_pct']
    if 'continuity_index' in rev.columns:
        rev_sleep['polar_continuity_index'] = rev['continuity_index']
    
    context_cols = [
        'Fecha',
        'polar_sleep_duration_min', 'polar_sleep_span_min',
        'polar_deep_pct', 'polar_rem_pct',
        'polar_efficiency_pct', 'polar_continuity', 'polar_continuity_index',
        'polar_interruptions_long', 'polar_sleep_score',
        'polar_night_rmssd', 'polar_night_rri', 'polar_night_resp',
    ]
    context = rev_sleep[[c for c in context_cols if c in rev_sleep.columns]].copy()
    context = context.sort_values('Fecha').reset_index(drop=True)
    
    # --- Sleep percentiles ---
    dur = context['polar_sleep_duration_min'].dropna()
    context['sleep_dur_p10'] = float(dur.quantile(0.10)) if len(dur) >= 20 else np.nan
    context['sleep_dur_p90'] = float(dur.quantile(0.90)) if len(dur) >= 20 else np.nan
    
    intl = context.get('polar_interruptions_long', pd.Series(dtype=float)).dropna()
    context['sleep_int_p90'] = float(intl.quantile(0.90)) if len(intl) >= 20 else np.nan
    
    return context


# =============================================================================
# PART 2: V4-lite decisor WITH veto agudo (modified from endurance_v4lite.py)
# =============================================================================

VERDE = "VERDE"
AMBAR = "ÁMBAR"
ROJO  = "ROJO"
NO    = "NO"
GATE_ORDER = {VERDE: 0, AMBAR: 1, ROJO: 2}

SWC_FLOOR = 0.04879  # ln(1.05)
VETO_MULT = 2.0      # veto if raw drops > 2×SWC below base60


def robust_sd(x):
    x = np.asarray(x, dtype=float)
    x = x[np.isfinite(x)]
    if x.size == 0:
        return float("nan")
    med = np.median(x)
    mad = np.median(np.abs(x - med))
    return float(1.4826 * mad)


def last_n_valid_mean(values, valid, n, i):
    take = []
    j = i
    while j >= 0 and len(take) < n:
        if bool(valid[j]) and np.isfinite(values[j]):
            take.append(float(values[j]))
        j -= 1
    if not take:
        return (float("nan"), 0)
    return (float(np.mean(take)), len(take))


def window_mask(dates, i, days):
    t = dates[i]
    lo = t - np.timedelta64(days, "D")
    return (dates >= lo) & (dates < t)


def window_stats(values, valid, wmask, swc_mult):
    m = wmask & valid & np.isfinite(values)
    x = values[m].astype(float)
    n = int(x.size)
    if n == 0:
        return (float("nan"), float("nan"), 0)
    base = float(np.median(x))
    sd = robust_sd(x)
    swc = float(swc_mult * sd) if np.isfinite(sd) else float("nan")
    return (base, swc, n)


def residual_tag(res_z, t1=0.5, t2=1.0, t3=2.0):
    if not np.isfinite(res_z):
        return ""
    if res_z >= t3: return "+++"
    if res_z >= t2: return "++"
    if res_z >= t1: return "+"
    if res_z <= -t3: return "---"
    if res_z <= -t2: return "--"
    if res_z <= -t1: return "-"
    return ""


def _downgrade(g, k=1):
    if g == VERDE: return AMBAR if k >= 1 else VERDE
    if g == AMBAR: return ROJO if k >= 1 else AMBAR
    return g

def _upgrade(g, k=1):
    if g == ROJO: return AMBAR if k >= 1 else ROJO
    if g == AMBAR: return VERDE if k >= 1 else AMBAR
    return g


def build_v4_final(core: pd.DataFrame, context: pd.DataFrame) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """
    Build FINAL and DASHBOARD with v4 enhancements:
    - Veto agudo (bypass ROLL3 on acute drops)
    - reason_text (contextual explanations)
    - SWC floor
    """
    
    df = core.copy()
    df["Fecha_dt"] = pd.to_datetime(df["Fecha"], errors="coerce")
    df = df.sort_values("Fecha_dt").reset_index(drop=True)
    dates = df["Fecha_dt"].to_numpy(dtype="datetime64[ns]")
    N = len(df)
    
    # Merge context by Fecha
    ctx = context.copy()
    ctx['Fecha'] = ctx['Fecha'].astype(str)
    df['Fecha_str'] = df['Fecha'].astype(str)
    ctx_lookup = ctx.set_index('Fecha')
    
    # Signals
    ln_today = pd.to_numeric(df["lnRMSSD"], errors="coerce").to_numpy(dtype=float)
    hr_today = pd.to_numeric(df["HR_stable"], errors="coerce").to_numpy(dtype=float)
    rmssd_today = pd.to_numeric(df["RMSSD_stable"], errors="coerce").to_numpy(dtype=float)
    rrbar_s = pd.to_numeric(df["RRbar_s"], errors="coerce").to_numpy(dtype=float)
    
    # Clean/invalid/quality_flag
    is_numeric = np.isfinite(ln_today) & np.isfinite(hr_today) & np.isfinite(rmssd_today)
    is_invalid = (df["Calidad"].astype(str) == "INVALID") | (~is_numeric) | df["Fecha_dt"].isna().to_numpy()
    is_clean = (df["Calidad"].astype(str) == "OK") & is_numeric & (~is_invalid)
    quality_flag = (~is_clean) & (~is_invalid)
    
    # Config
    swc_mult = 0.5
    min_roll3 = 3
    min_base60 = 30
    min_base42 = 21
    min_base28 = 14
    
    # ROLL3 (solo clean)
    ln_used = np.full(N, np.nan, dtype=float)
    hr_used = np.full(N, np.nan, dtype=float)
    n_roll3 = np.zeros(N, dtype=int)
    for i in range(N):
        mu_ln, n_ln = last_n_valid_mean(ln_today, is_clean, 3, i)
        mu_hr, n_hr = last_n_valid_mean(hr_today, is_clean, 3, i)
        ln_used[i] = mu_ln
        hr_used[i] = mu_hr
        n_roll3[i] = int(min(n_ln, n_hr))
    
    # Arrays for results
    ln_base60 = np.full(N, np.nan); hr_base60 = np.full(N, np.nan)
    n_base60 = np.zeros(N, dtype=int)
    swc_ln60 = np.full(N, np.nan); swc_hr60 = np.full(N, np.nan)
    
    n_base42 = np.zeros(N, dtype=int); n_base28 = np.zeros(N, dtype=int)
    
    gate_base60 = np.array([NO]*N, dtype=object)
    razon_base60 = np.array([""]*N, dtype=object)
    gate_shadow42 = np.array([NO]*N, dtype=object)
    razon_shadow42 = np.array([""]*N, dtype=object)
    gate_shadow28 = np.array([NO]*N, dtype=object)
    razon_shadow28 = np.array([""]*N, dtype=object)
    
    d_ln = np.full(N, np.nan); d_hr = np.full(N, np.nan)
    
    residual_ln = np.full(N, np.nan)
    residual_z = np.full(N, np.nan)
    residual_tag_arr = np.array([""]*N, dtype=object)
    
    # V4 NEW arrays
    veto_agudo = np.array([False]*N, dtype=bool)
    ln_pre_veto = np.full(N, np.nan)
    swc_ln_floor_arr = np.full(N, np.nan)
    reason_parts: List[List[str]] = [[] for _ in range(N)]
    
    ln_rr = np.full(N, np.nan)
    with np.errstate(divide="ignore", invalid="ignore"):
        ln_rr = np.log(rrbar_s)
    
    # ========================================
    # Main loop: baselines + VETO AGUDO + gate
    # ========================================
    for i in range(N):
        if is_invalid[i]:
            gate_base60[i] = NO; razon_base60[i] = "CAL/STAB/ART/NaN"
            gate_shadow42[i] = NO; razon_shadow42[i] = "CAL/STAB/ART/NaN"
            gate_shadow28[i] = NO; razon_shadow28[i] = "CAL/STAB/ART/NaN"
            continue
        
        if n_roll3[i] < min_roll3:
            gate_base60[i] = NO; razon_base60[i] = "ROLL3_INSUF"
            gate_shadow42[i] = NO; razon_shadow42[i] = "ROLL3_INSUF"
            gate_shadow28[i] = NO; razon_shadow28[i] = "ROLL3_INSUF"
            continue
        
        # ===== BASE60 =====
        w60 = window_mask(dates, i, 60)
        b_ln, sw_ln, n_ln = window_stats(ln_today, is_clean, w60, swc_mult)
        b_hr, sw_hr, n_hr = window_stats(hr_today, is_clean, w60, swc_mult)
        n60 = int(min(n_ln, n_hr))
        
        ln_base60[i] = b_ln; hr_base60[i] = b_hr; n_base60[i] = n60
        swc_ln60[i] = sw_ln; swc_hr60[i] = sw_hr
        
        if n60 < min_base60:
            gate_base60[i] = NO; razon_base60[i] = "BASE60_INSUF"
        elif (not np.isfinite(sw_ln)) or (not np.isfinite(sw_hr)) or sw_ln == 0 or sw_hr == 0:
            gate_base60[i] = NO; razon_base60[i] = "SWC_NAN/0"
        else:
            # ===== VETO AGUDO =====
            swc_v4 = max(sw_ln, SWC_FLOOR)
            swc_ln_floor_arr[i] = swc_v4
            
            if (is_clean[i] and np.isfinite(ln_today[i]) and np.isfinite(b_ln)
                and ln_today[i] < (b_ln - VETO_MULT * swc_v4)):
                veto_agudo[i] = True
                ln_pre_veto[i] = ln_used[i]
                ln_used[i] = ln_today[i]   # force raw
                hr_used[i] = hr_today[i]   # force raw HR too
                reason_parts[i].append(
                    f"Caída aguda HRV: raw={ln_today[i]:.3f} vs base={b_ln:.3f} "
                    f"(drop={ln_today[i]-b_ln:.3f}, umbral=-{VETO_MULT*swc_v4:.3f})"
                )
            
            # Gate 2D (using potentially veto-adjusted ln_used/hr_used)
            dln = float(ln_used[i] - b_ln)
            dhr = float(hr_used[i] - b_hr)
            d_ln[i] = dln; d_hr[i] = dhr
            
            ln_bajo = dln < -sw_ln
            hr_alto = dhr > sw_hr
            
            if ln_bajo and hr_alto:
                gate_base60[i] = ROJO; razon_base60[i] = "2D_AMBOS"
            elif ln_bajo:
                gate_base60[i] = AMBAR; razon_base60[i] = "2D_LN"
            elif hr_alto:
                gate_base60[i] = AMBAR; razon_base60[i] = "2D_HR"
            else:
                gate_base60[i] = VERDE; razon_base60[i] = "2D_OK"
            
            # Saturación parasimpática (informativa)
            if dln > 2 * swc_v4:
                reason_parts[i].append(
                    f"HRV excesivamente alto (d_ln=+{dln:.3f} > 2×SWC={2*swc_v4:.3f}): posible saturación parasimpática"
                )
        
        # ===== SHADOW42 =====
        w42 = window_mask(dates, i, 42)
        b_ln42, sw_ln42, n_ln42 = window_stats(ln_today, is_clean, w42, swc_mult)
        b_hr42, sw_hr42, n_hr42 = window_stats(hr_today, is_clean, w42, swc_mult)
        nb42 = int(min(n_ln42, n_hr42)); n_base42[i] = nb42
        
        if nb42 < min_base42:
            gate_shadow42[i] = NO; razon_shadow42[i] = "BASE42_INSUF"
        elif (not np.isfinite(sw_ln42)) or (not np.isfinite(sw_hr42)) or sw_ln42 == 0 or sw_hr42 == 0:
            gate_shadow42[i] = NO; razon_shadow42[i] = "SWC_NAN/0"
        else:
            dln42 = float(ln_used[i] - b_ln42); dhr42 = float(hr_used[i] - b_hr42)
            if dln42 < -sw_ln42 and dhr42 > sw_hr42:
                gate_shadow42[i] = ROJO; razon_shadow42[i] = "2D_AMBOS"
            elif dln42 < -sw_ln42:
                gate_shadow42[i] = AMBAR; razon_shadow42[i] = "2D_LN"
            elif dhr42 > sw_hr42:
                gate_shadow42[i] = AMBAR; razon_shadow42[i] = "2D_HR"
            else:
                gate_shadow42[i] = VERDE; razon_shadow42[i] = "2D_OK"
        
        # ===== SHADOW28 =====
        w28 = window_mask(dates, i, 28)
        b_ln28, sw_ln28, n_ln28 = window_stats(ln_today, is_clean, w28, swc_mult)
        b_hr28, sw_hr28, n_hr28 = window_stats(hr_today, is_clean, w28, swc_mult)
        nb28 = int(min(n_ln28, n_hr28)); n_base28[i] = nb28
        
        if nb28 < min_base28:
            gate_shadow28[i] = NO; razon_shadow28[i] = "BASE28_INSUF"
        elif (not np.isfinite(sw_ln28)) or (not np.isfinite(sw_hr28)) or sw_ln28 == 0 or sw_hr28 == 0:
            gate_shadow28[i] = NO; razon_shadow28[i] = "SWC_NAN/0"
        else:
            dln28 = float(ln_used[i] - b_ln28); dhr28 = float(hr_used[i] - b_hr28)
            if dln28 < -sw_ln28 and dhr28 > sw_hr28:
                gate_shadow28[i] = ROJO; razon_shadow28[i] = "2D_AMBOS"
            elif dln28 < -sw_ln28:
                gate_shadow28[i] = AMBAR; razon_shadow28[i] = "2D_LN"
            elif dhr28 > sw_hr28:
                gate_shadow28[i] = AMBAR; razon_shadow28[i] = "2D_HR"
            else:
                gate_shadow28[i] = VERDE; razon_shadow28[i] = "2D_OK"
        
        # ===== RESIDUAL (BASE60) =====
        mfit = w60 & is_clean & np.isfinite(ln_rr) & np.isfinite(ln_today)
        if np.sum(mfit) >= min_base60 and np.isfinite(ln_rr[i]) and np.isfinite(ln_today[i]):
            x = ln_rr[mfit].astype(float)
            y = ln_today[mfit].astype(float)
            X = np.column_stack([np.ones_like(x), x])
            try:
                coef, *_ = np.linalg.lstsq(X, y, rcond=None)
                a, b = float(coef[0]), float(coef[1])
                yhat = a + b * float(ln_rr[i])
                residual_ln[i] = float(ln_today[i] - yhat)
                resid_train = y - (a + b * x)
                sd_res = robust_sd(resid_train)
                swc_res = swc_mult * sd_res if np.isfinite(sd_res) else float("nan")
                if np.isfinite(swc_res) and swc_res != 0:
                    residual_z[i] = float(residual_ln[i] / swc_res)
                    residual_tag_arr[i] = residual_tag(residual_z[i])
            except Exception:
                pass
    
    # ===== Decision mode (O2_SHADOW) =====
    decision_mode = "O2_SHADOW"
    gate_final = gate_base60.copy()
    gate_final_delta = np.zeros(N, dtype=int)
    decision_path = np.array(["BASE60_ONLY"]*N, dtype=object)
    override_reason = np.array([""]*N, dtype=object)
    
    # Badge
    gate_badge = np.array([str(g) + str(t) for g, t in zip(gate_final, residual_tag_arr)], dtype=object)
    
    # ===== Action + accumulation =====
    Color_operativo = gate_final.copy()
    Action = np.array(["SUAVE_O_DESCANSO"]*N, dtype=object)
    Action_detail = np.array(["SUAVE"]*N, dtype=object)
    
    for i in range(N):
        gf = gate_final[i]
        qf = bool(quality_flag[i])
        if gf == VERDE and not qf:
            Action[i] = "INTENSIDAD_OK"; Action_detail[i] = "EJECUTAR_PLAN"
        elif gf == AMBAR and not qf:
            Action[i] = "Z2_O_TEMPO_SUAVE"; Action_detail[i] = "SIN_HIIT"
        else:
            Action[i] = "SUAVE_O_DESCANSO"
            Action_detail[i] = "SUAVE_QUALITY" if (qf and gf in (VERDE, AMBAR, ROJO)) else "SUAVE"
    
    bad_streak = np.zeros(N, dtype=int)
    for i in range(N):
        if gate_final[i] in (ROJO, NO):
            bad_streak[i] = (bad_streak[i-1] + 1) if i > 0 else 1
    
    bad_7d = np.zeros(N, dtype=int)
    for i in range(N):
        lo = max(0, i-6)
        bad_7d[i] = int(np.sum(np.isin(gate_final[lo:i+1], [ROJO, NO])))
    
    for i in range(N):
        if Action_detail[i] == "SUAVE_QUALITY":
            continue
        if gate_final[i] in (ROJO, NO) and (bad_streak[i] >= 2 or bad_7d[i] >= 3):
            Action_detail[i] = "DESCARGA"
    
    # ===== Warning baseline60_degraded =====
    # healthy85 mode
    clean_mask = is_clean & pd.to_numeric(df["RMSSD_stable"], errors='coerce').notna().to_numpy()
    sub = df.loc[clean_mask, ["Fecha_dt", "RMSSD_stable", "HR_stable"]].sort_values("Fecha_dt").copy()
    sub["RMSSD_med7"] = sub["RMSSD_stable"].rolling(7, min_periods=3).median()
    sub["HR_med7"] = sub["HR_stable"].rolling(7, min_periods=3).median()
    
    hs = pd.to_datetime("2025-07-01"); he = pd.to_datetime("2025-09-30")
    in_period = (sub["Fecha_dt"] >= hs) & (sub["Fecha_dt"] <= he)
    healthy_rmssd = float(np.nanmedian(sub.loc[in_period, "RMSSD_med7"])) if in_period.any() else float("nan")
    healthy_hr = float(np.nanmedian(sub.loc[in_period, "HR_med7"])) if in_period.any() else float("nan")
    healthy_period = "2025-07-01..2025-09-30"
    
    warning_threshold = float(0.85 * healthy_rmssd) if np.isfinite(healthy_rmssd) else float("nan")
    rmssd_base60_equiv = np.exp(ln_base60.astype(float))
    
    if np.isfinite(warning_threshold):
        baseline60_degraded = (rmssd_base60_equiv < warning_threshold) & np.isfinite(rmssd_base60_equiv)
    else:
        baseline60_degraded = np.array([False]*N, dtype=bool)
    
    # ===== REASON_TEXT (contextual, using sleep.csv) =====
    for i in range(N):
        fecha_str = df.iloc[i]['Fecha_str'] if 'Fecha_str' in df.columns else str(df.iloc[i]['Fecha'])
        
        # Quality override
        if quality_flag[i] and gate_final[i] in (VERDE, AMBAR):
            reason_parts[i].append("Dato dudoso: limitar a Z1-Z2 máx 90min")
        
        # Context from sidecar
        if fecha_str in ctx_lookup.index:
            ctx_row = ctx_lookup.loc[fecha_str]
            
            # Sleep context
            sleep_dur = ctx_row.get('polar_sleep_duration_min', np.nan)
            sleep_int = ctx_row.get('polar_interruptions_long', np.nan)
            sleep_score = ctx_row.get('polar_sleep_score', np.nan)
            sleep_dur_p10 = ctx_row.get('sleep_dur_p10', np.nan)
            sleep_int_p90 = ctx_row.get('sleep_int_p90', np.nan)
            
            sleep_bad = False
            if np.isfinite(sleep_dur) and np.isfinite(sleep_dur_p10):
                if sleep_dur < sleep_dur_p10:
                    reason_parts[i].append(f"Noche corta ({sleep_dur:.0f}min < P10={sleep_dur_p10:.0f})")
                    sleep_bad = True
            if np.isfinite(sleep_int) and np.isfinite(sleep_int_p90):
                if sleep_int > sleep_int_p90:
                    reason_parts[i].append(f"Noche fragmentada ({sleep_int:.0f} interr > P90={sleep_int_p90:.0f})")
                    sleep_bad = True
            
            # Night RMSSD context (Spearman ρ=0.52 with morning)
            night_rmssd = ctx_row.get('polar_night_rmssd', np.nan)
            if np.isfinite(night_rmssd):
                if gate_final[i] == VERDE and night_rmssd < 25:
                    reason_parts[i].append(f"VERDE pero nightly_rmssd bajo ({night_rmssd:.0f}ms): vigilar")
                elif gate_final[i] == ROJO and night_rmssd > 45:
                    reason_parts[i].append(f"ROJO con nightly_rmssd alto ({night_rmssd:.0f}ms): posible confusor")
            
            # Load context
            load_3d = ctx_row.get('intervals_load_3d', np.nan)
            load_3d_p90 = ctx_row.get('load_3d_p90', np.nan)
            tsb = ctx_row.get('intervals_tsb', np.nan)
            load_yday = ctx_row.get('intervals_load_yday', np.nan)
            
            if np.isfinite(load_3d) and np.isfinite(load_3d_p90) and load_3d > load_3d_p90:
                reason_parts[i].append(f"Carga acumulada alta (3d={load_3d:.0f} > P90={load_3d_p90:.0f})")
            
            if np.isfinite(tsb) and tsb < -25:
                reason_parts[i].append(f"Fatiga profunda (TSB={tsb:.0f})")
            
            # Coherence checks
            if gate_final[i] == ROJO and np.isfinite(load_yday) and load_yday < 30 and not sleep_bad:
                reason_parts[i].append("ROJO sin carga previa ni sueño malo: revisar otros factores")
            
            if gate_final[i] == VERDE and np.isfinite(tsb) and tsb < -20:
                reason_parts[i].append(f"VERDE con fatiga acumulada (TSB={tsb:.0f}): precaución intensidad")
    
    # Build reason_text
    reason_text = np.array([" | ".join(parts) if parts else "" for parts in reason_parts], dtype=object)
    
    # ===== Placeholders =====
    flag_sistemico = np.array([False]*N, dtype=bool)
    flag_razon = np.array([""]*N, dtype=object)
    
    # ===== Build FINAL DataFrame =====
    final = pd.DataFrame({
        "Fecha": df["Fecha"].astype(str),
        "Calidad": df["Calidad"].astype(str),
        "HRV_Stability": df["HRV_Stability"].astype(str),
        "Artifact_pct": pd.to_numeric(df["Artifact_pct"], errors="coerce"),
        "Tiempo_Estabilizacion": pd.to_numeric(df["Tiempo_Estabilizacion"], errors="coerce"),
        "HR_today": hr_today,
        "RMSSD_stable": rmssd_today,
        "lnRMSSD_today": ln_today,
        "lnRMSSD_used": ln_used,
        "HR_used": hr_used,
        "n_roll3": n_roll3,
        "ln_base60": ln_base60,
        "HR_base60": hr_base60,
        "n_base60": n_base60,
        "SWC_ln": swc_ln60,
        "SWC_HR": swc_hr60,
        "d_ln": d_ln,
        "d_HR": d_hr,
        "gate_base60": gate_base60,
        "gate_razon_base60": razon_base60,
        "gate_shadow42": gate_shadow42,
        "gate_razon_shadow42": razon_shadow42,
        "n_base42": n_base42,
        "gate_shadow28": gate_shadow28,
        "gate_razon_shadow28": razon_shadow28,
        "n_base28": n_base28,
        "decision_mode": decision_mode,
        "gate_final": gate_final,
        "gate_final_delta": gate_final_delta,
        "decision_path": decision_path,
        "override_reason": override_reason,
        "residual_ln": residual_ln,
        "residual_z": residual_z,
        "residual_tag": residual_tag_arr,
        "gate_badge": gate_badge,
        "quality_flag": quality_flag.astype(bool),
        "Color_operativo": Color_operativo,
        "Action": Action,
        "Action_detail": Action_detail,
        "bad_streak": bad_streak,
        "bad_7d": bad_7d,
        "baseline60_degraded": baseline60_degraded.astype(bool),
        "healthy_rmssd": healthy_rmssd,
        "healthy_hr": healthy_hr,
        "healthy_period": healthy_period,
        "flag_sistemico": flag_sistemico.astype(bool),
        "flag_razon": flag_razon,
        "warning_threshold": warning_threshold,
        "warning_mode": "healthy85",
        # V4 NEW
        "veto_agudo": veto_agudo.astype(bool),
        "ln_pre_veto": ln_pre_veto,
        "swc_ln_floor": swc_ln_floor_arr,
        "reason_text": reason_text,
    })
    
    # Dashboard
    dashboard = final[[
        "Fecha", "Calidad", "HR_today", "RMSSD_stable", "gate_badge", "Action",
        "gate_razon_base60", "decision_path", "baseline60_degraded", "reason_text",
    ]].copy()
    
    return final, dashboard


# =============================================================================
# PART 3: Validation and comparison
# =============================================================================

def validate_and_compare(final_v4, final_old_path):
    """Compare v4 output with current production FINAL."""
    old = pd.read_csv(final_old_path)
    old['Fecha'] = old['Fecha'].astype(str)
    final_v4['Fecha'] = final_v4['Fecha'].astype(str)
    
    merged = old.merge(final_v4, on='Fecha', suffixes=('_old', '_v4'))
    
    print("\n" + "="*60)
    print("VALIDATION: v4 vs production")
    print("="*60)
    
    # Gate changes
    gate_changed = merged[merged['gate_final_old'] != merged['gate_final_v4']]
    print(f"\nGate changes: {len(gate_changed)} / {len(merged)} days")
    for _, r in gate_changed.iterrows():
        print(f"  {r['Fecha']}: {r['gate_final_old']} → {r['gate_final_v4']}"
              f"  veto={r['veto_agudo']}"
              f"  reason={r['reason_text'][:80]}")
    
    # Veto agudo stats
    veto_days = final_v4[final_v4['veto_agudo'] == True]
    print(f"\nVeto agudo activated: {len(veto_days)} days")
    for _, r in veto_days.iterrows():
        print(f"  {r['Fecha']}: ln_pre_veto={r['ln_pre_veto']:.3f} → ln_used={r['lnRMSSD_used']:.3f}"
              f"  gate={r['gate_final']}")
    
    # Reason_text coverage
    has_reason = final_v4['reason_text'].str.len() > 0
    print(f"\nDays with reason_text: {has_reason.sum()} / {len(final_v4)}")
    
    # Gate distribution comparison
    print(f"\nGate distribution:")
    for g in [VERDE, AMBAR, ROJO, NO]:
        n_old = (merged['gate_final_old'] == g).sum()
        n_v4 = (merged['gate_final_v4'] == g).sum()
        print(f"  {g}: {n_old} → {n_v4} (delta {n_v4-n_old:+d})")
    
    return gate_changed


# =============================================================================
# MAIN
# =============================================================================

if __name__ == "__main__":
    print("Loading data sources...")
    core, rev, acts = load_all_sources()
    
    print(f"CORE: {len(core)} days ({core['Fecha'].min()} → {core['Fecha'].max()})")
    
    print("\nBuilding sleep.csv (historical Polar sleep only)...")
    context = build_context(rev, acts)
    print(f"Context: {len(context)} rows")
    print(f"  Sleep coverage: {context['polar_sleep_duration_min'].notna().sum()} days")
    print(f"  Night RMSSD coverage: {context['polar_night_rmssd'].notna().sum() if 'polar_night_rmssd' in context.columns else 0} days")
    print(f"  (Training load now in sessions_day.csv via build_sessions.py)")
    
    print("\nBuilding FINAL v4 (with veto agudo + reason_text)...")
    final_v4, dashboard_v4 = build_v4_final(core, context)
    print(f"FINAL v4: {final_v4.shape}")
    print(f"DASHBOARD v4: {dashboard_v4.shape}")
    
    # Validate against production
    changes = validate_and_compare(final_v4, "/mnt/user-data/uploads/ENDURANCE_HRV_master_FINAL.csv")
    
    # Save
    out_dir = Path("/mnt/user-data/outputs")
    
    final_v4.to_csv(out_dir / "ENDURANCE_HRV_master_FINAL_v4.csv", index=False)
    dashboard_v4.to_csv(out_dir / "ENDURANCE_HRV_master_DASHBOARD_v4.csv", index=False)
    context.to_csv(out_dir / "ENDURANCE_HRV_sleep.csv", index=False)
    
    print(f"\n✅ Saved to {out_dir}:")
    print(f"  ENDURANCE_HRV_master_FINAL_v4.csv ({final_v4.shape[0]} rows, {final_v4.shape[1]} cols)")
    print(f"  ENDURANCE_HRV_master_DASHBOARD_v4.csv ({dashboard_v4.shape[0]} rows, {dashboard_v4.shape[1]} cols)")
    print(f"  ENDURANCE_HRV_sleep.csv ({context.shape[0]} rows, {context.shape[1]} cols)")
